[tool.poetry]
name = "practice"
version = "0.1.0"
description = "Project to practice the code from the thinkstats book"
authors = ["samantoz <samantoz@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
numpy = "*"
pandas = "*"
matplotlib = "*"
scipy = "*"
jupyter = "*"

[tool.poetry.dev-dependencies]
pytest = "^7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
